
import = [
    "~/.config/alacritty/repothemes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMonoNL Nerd Font" 

size = 16
