
general.import = [
    "~/.config/alacritty/repothemes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMonoNL Nerd Font" 

size = 16

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },# Skip word left
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },# Skip word right
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },# jump word start
  { key = "Right", mods = "Command", chars =  "\u001bOF" },# jump word end
  { key = "Back",  mods = "Command", chars = "\u0015"    },# Delete line
  { key = "Back",  mods = "Command", chars = "\u0017"    },# Delete word
]

# Add these lines to allow full color support in terminal applications
[colors]
draw_bold_text_with_bright_colors = true


